version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: aleksey767
      POSTGRES_PASSWORD: andersen
      POSTGRES_DB: ticket_to_ride
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/src/main/java/com/andersen/ticketToRide/init.sql
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ticket_to_ride
      SPRING_DATASOURCE_USERNAME: aleksey767
      SPRING_DATASOURCE_PASSWORD: andersen

volumes:
  postgres_data: